export const checkItems = [
  { key: "engineOil", label: "שמן מנוע" },
  { key: "coolantWater", label: "מים רדיאטור" },
  { key: "windshieldWasherFluid", label: "מים שמשות" },
  { key: "ureaOver50", label: "אוריה מעל 50%" },
  { key: "dieselOver50", label: "סולר מעל 50%" },
  { key: "lightsAndMirrors", label: "פנסים ומראות" },
  { key: "spareWheel", label: "גלגל תחיפי" },
  { key: "wheelChangeKit", label: "ציוד החלפת גלגל" },
  { key: "compulsoryInsuranceValid", label: "ביטוח חובה תקף" },
  { key: "propertyInsuranceValid", label: "ביטוח רכוש תקף" },
  { key: "vehicleTest", label: "טסט רכב" },
  { key: "doorOpening", label: "פתיחת דלתות" },
  { key: "trolley", label: "עגלה" },
  { key: "cameras", label: "מצלמות" },
  { key: "drivingSystems", label: "מערכות נהיגה" },
  { key: "cellPhone", label: "פלאפון" },
  { key: "externalInternalCleaning", label: "ניקיון חיצוני ופנימי" },
  { key: "winchCap", label: "פקק מנוף – כמות 1" },
  { key: "winchBattery", label: "סוללה מנוף – כמות 2" },
  { key: "winchRemote", label: "שלט מנוף – כמות 2" },
  { key: "winchChargingCable", label: "כבל טעינה מנוף – כמות 1" },
  { key: "colorKit", label: "ספרי צבע + ניילון + מפתח אלן + 2 ברגים" },
  { key: "phoneCharger", label: "מטען פלאפון" },
  { key: "fridge", label: "מקרר" },
  { key: "returnLight", label: "פנס החזרות" },
];

export const vehicleInspectionLabels = {
  vehicleNumber: "מספר רכב",
  registrationNumber: "מספר רישוי",
  driverName: "שם נהג",
  inspectionDate: "תאריך בדיקה",
  inspectionTime: "שעת בדיקה",
  odometerReading: "קריאת מד אוץ",
  paintAndBody: "צבע ומרכב",
  spareKeys: "מפתחות רזרביים",
  vehicleDamageDiagram: "תרשים נזקי רכב",
  notes: "הערות",
  eventsObligatingReporting: "אירועים המחייבים דיווח",
  driverSignature: "חתימת נהג",
  // Status labels for 'ok' and 'not_ok'
  ok: "תקין",
  not_ok: "לא תקין",
};
