//prettier-ignore
export const checkItems = [
  { key: "engineOil", label: "שמן מנוע" },
  { key: "coolantWater", label: "מים רדיאטור" },
  { key: "windshieldWasherFluid", label: "מים שמשות" },
  { key: "battery", label: "מצבר" },
  { key: "fiveLBackupFuses", label: "פנס חירום" },
  { key: "tireToolKit", label: "אופס חירום כמות 5" },
  { key: "spareTire", label: "ערכת גלגל 5 כמות 1" },
  { key: "spareTireToolKit", label: "ערכת גלגל M כמות 2" },
  { key: "reflectiveVest50Percent", label: "ערכת גלגל L כמות 2" },
  { key: "reflectiveTriangle50Percent", label: "ערכת גלגל XL כמות 1" },
  { key: "firstAidKit", label: "ערכת תמיכה S כמות 1" },
  { key: "fireExtinguisher", label: "ערכת תמיכה M כמות 1" },
  { key: "jack", label: "ערכת תמיכה L כמות 1" },
  { key: "tireIron", label: "ערכת תמיכה XL כמות 1" },
  { key: "spareWheel", label: "פיקוד מנוף כמות 1" },
  { key: "spareWheelMountingKit", label: "סוללת מנוף כמות 2" },
  { key: "safetyVestQty1", label: "שלט מנוף כמות 2" },
  { key: "safetyVestQty2", label: "כבל טעינה שלט מנוף כמות 1" },
  { key: "safetyVestQty3", label: "ספרי צבע + מלטש" },
  { key: "safetyVestQty4", label: "מפתח אלן + 2 ברגים" },
  { key: "safetyVestQty5", label: "אוריה מעל 50%" },
  { key: "towingHookQty1", label: "סולר מעל 50%" },
  { key: "towingHookQty2", label: "פנסים ומראות" },
  { key: "jumperCablesQty2", label: "גלגל חילופי" },
  { key: "wheelChocksQty2", label: "ציוד להחלפת גלגל" },
  { key: "cellphoneChargerQty1", label: "ביטוח חובה תקף" },
];

export const vehicleInspectionLabels = {
  vehicleNumber: "מספר רכב",
  registrationNumber: "מספר רישוי",
  driverName: "שם נהג",
  inspectionDate: "תאריך בדיקה",
  inspectionTime: "שעת בדיקה",
  odometerReading: "קריאת מד אוץ",
  paintAndBody: "צבע ומרכב",
  spareKeys: "מפתחות רזרביים",
  vehicleDamageDiagram: "תרשים נזקי רכב",
  notes: "הערות",
  eventsObligatingReporting: "אירועים המחייבים דיווח",
  driverSignature: "חתימת נהג",
  // Status labels for 'ok' and 'not_ok'
  ok: "תקין",
  not_ok: "לא תקין",
};
