CREATE TYPE inspection_status AS ENUM ('ok', 'not_ok');

CREATE TABLE vehicle_inspections (
    id BIGSERIAL PRIMARY KEY,
    driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE NOT NULL,
    car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
    vehicle_number VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    driver_name VARCHAR(255) NOT NULL,
    inspection_date VARCHAR(255) NOT NULL,
    inspection_time VARCHAR(255),
    odometer_reading VARCHAR(255) NOT NULL,
    engine_oil inspection_status NOT NULL,
    coolant_water inspection_status NOT NULL,
    windshield_washer_fluid inspection_status NOT NULL,
    battery inspection_status NOT NULL,
    five_l_backup_fuses inspection_status NOT NULL,
    tire_tool_kit inspection_status NOT NULL,
    spare_tire inspection_status NOT NULL,
    spare_tire_tool_kit inspection_status NOT NULL,
    reflective_vest_50_percent inspection_status NOT NULL,
    reflective_triangle_50_percent inspection_status NOT NULL,
    first_aid_kit inspection_status NOT NULL,
    fire_extinguisher inspection_status NOT NULL,
    jack inspection_status NOT NULL,
    tire_iron inspection_status NOT NULL,
    spare_wheel inspection_status NOT NULL,
    spare_wheel_mounting_kit inspection_status NOT NULL,
    safety_vest_qty_1 inspection_status NOT NULL,
    safety_vest_qty_2 inspection_status NOT NULL,
    safety_vest_qty_3 inspection_status NOT NULL,
    safety_vest_qty_4 inspection_status NOT NULL,
    safety_vest_qty_5 inspection_status NOT NULL,
    towing_hook_qty_1 inspection_status NOT NULL,
    towing_hook_qty_2 inspection_status NOT NULL,
    jumper_cables_qty_2 inspection_status NOT NULL,
    wheel_chocks_qty_2 inspection_status NOT NULL,
    cellphone_charger_qty_1 inspection_status NOT NULL,
    paint_and_body TEXT NOT NULL,
    spare_keys TEXT NOT NULL,
    vehicle_damage_diagram JSONB NOT NULL,
    notes TEXT,
    events_obligating_reporting TEXT,
    driver_signature TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_vehicle_inspections_driver_id ON vehicle_inspections(driver_id);
CREATE INDEX idx_vehicle_inspections_car_id ON vehicle_inspections(car_id);
